spring.application.name=mySpringAi_MCP_Client

################ Log 相關設定 ################
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

# 開啟 PrettyLoggerAdvisor 與 SimpleLoggerAdvisor 的 DEBUG 等級日誌，用來觀察 ChatClient 的 prompt/response 流程。
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG
logging.level.com.example.myspringai_mcp_client.advisor.PrettyLoggerAdvisor=DEBUG

################ LLM model OpenAI 設定 ################
# OpenAI api key
spring.ai.openai.api-key=${OPENAI_API_KEY:}
# OpenAI-model type
spring.ai.openai.chat.model=gpt-4o-mini

################ MCP Client 相關設定 ################
# 設定一個叫做 mymcp 的 streamable HTTP MCP server connection 去連線到一個已經存在的 MCP server：http://localhost:8090/mcp
# 若尚未啟動 HTTP MCP Server，請先將以下兩行註解掉
# spring.ai.mcp.client.streamable-http.connections.mymcp.url=http://localhost:8090
# spring.ai.mcp.client.streamable-http.connections.mymcp.endpoint=/mcp

# npx @modelcontextprotocol/inspector
# 啟動一個本機 MCP Inspector UI
#   → 讓你連到 MCP Server
#   → 查看 server 提供哪些 tools/resources/prompts
#   → 手動測試 tool call
#   → 看 tool schema、輸入參數、執行結果

# git@github.com:tonysk0210/mySpringAiMcpTestingRepo.git